import { CategoryExamples } from './types';

export const HIERARCHY_EXAMPLES: CategoryExamples = {
  "category": "Hierarchy (层级结构)",
  "sub_categories": [
    {
      "type": "Tree Tech Capsule (科技树-胶囊节点)",
      "example_id": "hierarchy-tree-tech-style-capsule-item",
      "syntax": "infographic hierarchy-tree-tech-style-capsule-item\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Tree Curved Rounded (曲线树-圆角节点)",
      "example_id": "hierarchy-tree-curved-line-rounded-rect-node",
      "syntax": "infographic hierarchy-tree-curved-line-rounded-rect-node\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Tree Tech Badge Card (科技树-徽章卡片)",
      "example_id": "hierarchy-tree-tech-style-badge-card",
      "syntax": "infographic hierarchy-tree-tech-style-badge-card\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Tree BT Curved Badge (自下而上曲线树-徽章卡片)",
      "example_id": "hierarchy-tree-bt-curved-line-badge-card",
      "syntax": "infographic hierarchy-tree-bt-curved-line-badge-card\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Tree BT Curved Compact (自下而上曲线树-紧凑卡片)",
      "example_id": "hierarchy-tree-bt-curved-line-compact-card",
      "syntax": "infographic hierarchy-tree-bt-curved-line-compact-card\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Tree BT Curved Ribbon (自下而上曲线树-丝带卡片)",
      "example_id": "hierarchy-tree-bt-curved-line-ribbon-card",
      "syntax": "infographic hierarchy-tree-bt-curved-line-ribbon-card\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Tree BT Curved Rounded (自下而上曲线树-圆角节点)",
      "example_id": "hierarchy-tree-bt-curved-line-rounded-rect-node",
      "syntax": "infographic hierarchy-tree-bt-curved-line-rounded-rect-node\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Tree LR Curved Badge (自左向右曲线树-徽章卡片)",
      "example_id": "hierarchy-tree-lr-curved-line-badge-card",
      "syntax": "infographic hierarchy-tree-lr-curved-line-badge-card\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Tree RL Distributed Round (自右向左分布树-圆角节点)",
      "example_id": "hierarchy-tree-rl-distributed-origin-rounded-rect-node",
      "syntax": "infographic hierarchy-tree-rl-distributed-origin-rounded-rect-node\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Mindmap Branch Capsule (思维导图-梯度胶囊节点)",
      "example_id": "hierarchy-mindmap-branch-gradient-capsule-item",
      "syntax": "infographic hierarchy-mindmap-branch-gradient-capsule-item\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Mindmap Branch Circle Progress (思维导图-梯度圆环进度)",
      "example_id": "hierarchy-mindmap-branch-gradient-circle-progress",
      "syntax": "infographic hierarchy-mindmap-branch-gradient-circle-progress\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    },
    {
      "type": "Mindmap Branch Compact Card (思维导图-梯度紧凑卡片)",
      "example_id": "hierarchy-mindmap-branch-gradient-compact-card",
      "syntax": "infographic hierarchy-mindmap-branch-gradient-compact-card\\ndata\\n  title 用户调研\\n  desc 通过用户调研，了解用户需求和痛点，指导产品设计和优化\\n  items\\n    - label 用户调研\\n      value 100\\n      icon mingcute/user-question-line\\n      children\\n        - label 用户为什么要使用某个音乐平台\\n          value 80\\n          icon mingcute/music-2-ai-line\\n          children\\n            - label 用户从哪些渠道了解到这个平台\\n              value 70\\n              icon mingcute/ad-circle-line\\n            - label 这个平台是哪些方面吸引了用户\\n              value 65\\n              icon mingcute/mushroom-line\\n        - label 用户在什么场景下使用这个平台\\n          value 75\\n          icon mingcute/time-line\\n          children\\n            - label 用户从什么事件什么场景下使用\\n              value 60\\n              icon mingcute/calendar-time-add-line\\n            - label 用户在某个场景下用到哪些功能\\n              value 55\\n              icon mingcute/danmaku-line\\ntheme light\\n  palette antv",
      "data": { "title": "用户调研", "desc": "通过用户调研，了解用户需求和痛点，指导产品设计和优化", "items": [{ "label": "用户调研", "value": 100, "icon": "mingcute/user-question-line", "children": [{ "label": "用户为什么要使用某个音乐平台", "value": 80, "icon": "mingcute/music-2-ai-line", "children": [{ "label": "用户从哪些渠道了解到这个平台", "value": 70, "icon": "mingcute/ad-circle-line" }, { "label": "这个平台是哪些方面吸引了用户", "value": 65, "icon": "mingcute/mushroom-line" }] }, { "label": "用户在什么场景下使用这个平台", "value": 75, "icon": "mingcute/time-line", "children": [{ "label": "用户从什么事件什么场景下使用", "value": 60, "icon": "mingcute/calendar-time-add-line" }, { "label": "用户在某个场景下用到哪些功能", "value": 55, "icon": "mingcute/danmaku-line" }] }] }] }
    }
  ]
};
